<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\Pipely\Pipely.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <AssemblyName>Pipely.Stress</AssemblyName>
    <RootNamespace>PipelyStress</RootNamespace>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

</Project>
